on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Comment PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hello BBZW ! :wave:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          mode: upsert
          create-if-not-exists: true